/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blokus;

import java.awt.Color;
import javax.swing.JPanel;


/**
 *
 * @author Squall
 */
public class PartieGUI extends javax.swing.JFrame {

    /**
     * Creates new form Partie
     */
    public PartieGUI(String[] noms) {
        initComponents();
        btnRotation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blokus/btnRotation.png")));
        btnSymetrie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blokus/btnSymetrie.png")));
        this.j1Name.setText(noms[0]);
        this.j2Name.setText(noms[1]);
        if(noms[2] == null && noms[3] == null){
            this.j3Name.setText(noms[0]);
            this.j4Name.setText(noms[1]);
        } else if(noms[2] != null && noms[3] == null){
            this.j3Name.setText(noms[2]);
            this.j4Name.setText(noms[0]);
        } else if(noms[2] != null && noms[3] != null){
            this.j3Name.setText(noms[2]);
            this.j4Name.setText(noms[3]);
        }
        for(int i = 0; i < 20; i++){
            for(int j = 0; j < 20; j++){
                JPanel p = new JPanel();
                p.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                p.setSize(20, 20);
                p.setBackground(Color.white);
                p.setLocation(i*20, j*20);
                board.add(p);
            }
        }
        
    }

    private PartieGUI() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board = new javax.swing.JPanel();
        blueBox = new javax.swing.JPanel();
        greenBox = new javax.swing.JPanel();
        redBox = new javax.swing.JPanel();
        yellowBox = new javax.swing.JPanel();
        j1Name = new javax.swing.JLabel();
        j4Name = new javax.swing.JLabel();
        j2Name = new javax.swing.JLabel();
        j3Name = new javax.swing.JLabel();
        conteneurPieceJouee = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSymetrie = new javax.swing.JLabel();
        btnRotation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Partie");
        setPreferredSize(new java.awt.Dimension(1024, 700));
        setResizable(false);

        board.setBackground(new java.awt.Color(255, 255, 255));
        board.setLocation(new java.awt.Point(312, 160));
        board.setMaximumSize(new java.awt.Dimension(400, 400));
        board.setPreferredSize(new java.awt.Dimension(400, 400));
        board.setSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout boardLayout = new javax.swing.GroupLayout(board);
        board.setLayout(boardLayout);
        boardLayout.setHorizontalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        boardLayout.setVerticalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        blueBox.setBackground(new java.awt.Color(220, 220, 245));
        blueBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 200)));

        javax.swing.GroupLayout blueBoxLayout = new javax.swing.GroupLayout(blueBox);
        blueBox.setLayout(blueBoxLayout);
        blueBoxLayout.setHorizontalGroup(
            blueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        blueBoxLayout.setVerticalGroup(
            blueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        greenBox.setBackground(new java.awt.Color(204, 255, 204));
        greenBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 200, 0)));

        javax.swing.GroupLayout greenBoxLayout = new javax.swing.GroupLayout(greenBox);
        greenBox.setLayout(greenBoxLayout);
        greenBoxLayout.setHorizontalGroup(
            greenBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        greenBoxLayout.setVerticalGroup(
            greenBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        redBox.setBackground(new java.awt.Color(255, 204, 204));
        redBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 0, 0)));

        javax.swing.GroupLayout redBoxLayout = new javax.swing.GroupLayout(redBox);
        redBox.setLayout(redBoxLayout);
        redBoxLayout.setHorizontalGroup(
            redBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        redBoxLayout.setVerticalGroup(
            redBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        yellowBox.setBackground(new java.awt.Color(255, 255, 204));
        yellowBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 0)));

        javax.swing.GroupLayout yellowBoxLayout = new javax.swing.GroupLayout(yellowBox);
        yellowBox.setLayout(yellowBoxLayout);
        yellowBoxLayout.setHorizontalGroup(
            yellowBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        yellowBoxLayout.setVerticalGroup(
            yellowBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        j1Name.setText("joueur1");

        j4Name.setText("joueur4");

        j2Name.setText("joueur2");

        j3Name.setText("joueur3");

        conteneurPieceJouee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setText("Pièce jouée");

        btnSymetrie.setText(" ");

        btnRotation.setText(" ");

        javax.swing.GroupLayout conteneurPieceJoueeLayout = new javax.swing.GroupLayout(conteneurPieceJouee);
        conteneurPieceJouee.setLayout(conteneurPieceJoueeLayout);
        conteneurPieceJoueeLayout.setHorizontalGroup(
            conteneurPieceJoueeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteneurPieceJoueeLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(conteneurPieceJoueeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnSymetrie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRotation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        conteneurPieceJoueeLayout.setVerticalGroup(
            conteneurPieceJoueeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteneurPieceJoueeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(conteneurPieceJoueeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSymetrie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRotation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greenBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j4Name, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(conteneurPieceJouee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(j2Name, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(j3Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yellowBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(conteneurPieceJouee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(blueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j1Name)
                                .addGap(58, 58, 58)
                                .addComponent(j4Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(greenBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yellowBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j2Name)
                                .addGap(54, 54, 54)
                                .addComponent(j3Name)
                                .addGap(18, 18, 18)
                                .addComponent(redBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        board.getAccessibleContext().setAccessibleName("");
        board.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartieGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blueBox;
    private javax.swing.JPanel board;
    private javax.swing.JLabel btnRotation;
    private javax.swing.JLabel btnSymetrie;
    private javax.swing.JPanel conteneurPieceJouee;
    private javax.swing.JPanel greenBox;
    private javax.swing.JLabel j1Name;
    private javax.swing.JLabel j2Name;
    private javax.swing.JLabel j3Name;
    private javax.swing.JLabel j4Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel redBox;
    private javax.swing.JPanel yellowBox;
    // End of variables declaration//GEN-END:variables
}
